### ISSUE TITLE
"Change Endpoint" instructions don't work

### ISSUE THREAD

**Issue by arturstopa** [pmvalente171/iFetch-Chrome-Extension#4]
Running the extension without modifications yields following error: "Fetch API cannot load localhost:4000. URL scheme "localhost" is not supported.". I tried changing `MESSAGES_ENDPOINT` to "http://localhost:4000" (originally "localhost:4000"), but after making the change and adding the extension to the browser again change is not applied.

**Comment by pmvalente171** [comment]
Did you try building the application? The current version should already be updated with the correct endpoint
