### ISSUE TITLE
README small fix

### ISSUE THREAD

**Issue by RodrigoRalhaMoreira** [pmvalente171/iFetch-Chrome-Extension#5]
I think you changed the format of your messages now the field is "file", not "image".
The messages are sent to the backend with the following JSON format:
{
  utterance : string,
  user_id : string, 
  session_id : string,
  user_action : string,
  interface_selected_product_id: string,
  field: base64 byte dump
}

Receive these when interacting with the extension:
127.0.0.1 - - [16/Mar/2023 20:42:30] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2023 20:45:18] "OPTIONS / HTTP/1.1" 200 -
{'utterance': 'Hi!', 'user_id': '3679', 'session_id': '8075', 'user_action': '', 'interface_selected_product_id': '', 'file': None}
127.0.0.1 - - [16/Mar/2023 20:45:23] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [16/Mar/2023 20:46:07] "OPTIONS / HTTP/1.1" 200 -
{'utterance': 'test', 'user_id': '3679', 'session_id': '8075', 'user_action': '', 'interface_selected_product_id': '', 'file': None}

**Comment by pmvalente171** [comment]
Yup! I Changed it. Thanks for the warning!
